region: eu-west-1
hostport: 80
containerport: 80
role: frontend-application
environment: staging
iac: terraform-workspace-aws-test-applications-eu-west-1-apps-docs-staging-polygon-technology
team_name: documentation
docker_file: Dockerfile.review
docker_build_params: TARGET_BRANCH_REGEX=*staging*
memory: 1024
cpu: 512