name: Docs Dev Deployment
on:
  push:
    branches:
      - staging*
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      environment: "staging"
      core_app: "docs"
    secrets: inherit
